#!/usr/bin/env bash
#
# taskchk
#   taskwarrior database integrity verify, intended to run out of cron
#
# - checks for non-unique first 4 bytes task uuids
# - no duplicate labels
# - no fql same as any slashified project
# - all projects have labels
#
# scott@smemsh.net
# https://smemsh.net/src/.task/
# https://spdx.org/licenses/GPL-2.0
#

check_uuid_initial ()
{
	matches=$(
		task _uuids \
		| awk -F - '{print $1}' \
		| sort \
		| uniq -c \
		| sort -nrk 1,1 \
		| head -1 \
		| awk '{print $1}' \
	)

	if ((matches != 1))
	then echo "non-unique initial 4 bytes task uuid found" >&2; false; fi
}

# todo this should say what the duplicate labels are
check_duplicate_labels ()
{
	duplicates="$(
		task export \
		| jq -rc '.[] | {"label"} | join("")' \
		| sort \
		| uniq -d \
	)"
	if [[ $duplicates ]]
	then echo "duplicate labels"$'\n'"$duplicates" >&2; false; fi
}

check_collisions_fql_prj ()
{
	collisions="$(
		cat \
		<(task _unique project | sed s,\\.,/,g) \
		<(taskfqls) \
		| sort \
		| uniq -d \
	)"

	if [[ $collisions ]]
	then echo "fql-project collisions"$'\n'"$collisions" >&2; false; fi
}

check_all_labeled ()
{
	if (($(task label: export | jq '. | length')))
	then echo "unlabeled tasks found" >&2; false; fi
}


main ()
{
	check_uuid_initial || : $((errors++))
	check_all_labeled || : $((errors++))
	check_duplicate_labels || : $((errors++))
	check_collisions_fql_prj || : $((errors++))

	if ((errors))
	then echo "errors found in task database" >&2; false; exit; fi
}

main "$@"
