#!/usr/bin/env bash
#
# scott@smemsh.net
# https://github.com/smemsh/.task/
# https://spdx.org/licenses/GPL-2.0
#

bomb () { echo "$@" >&2; false; exit; }

taskl ()
{
	local taskid=${1:?}
	shift
	(($#)) && bomb "only one arg allowed"
	task $(taskid $taskid) "$@"
}
