#!/usr/bin/env bash
#
# timedo
#   start timew task "time/$1", with optional :hints, default "time/todo"
#
# scott@smemsh.net
# https://github.com/smemsh/.task/
# https://spdx.org/licenses/GPL-2.0
#

bomb () { echo "${0##*/}: ${@}" >&2; false; exit; }

declare -a hints args
for ((i = 1; i <= $#; i++)); do
	if [[ $arg =~ "^:" ]]
	then hints+=($arg); shift
	else args+=(time/$arg)
	fi
done

argc=${#args[@]}
((argc > 1)) && bomb "only zero or one fql, and timew :hints allowed"
((argc == 0)) && args=(todo)

timew start $args ${hints[@]}
