#!/usr/bin/env bash
#
# timedo
#   start timew task "time/$1", default "time/todo"
#
# scott@smemsh.net
# https://github.com/smemsh/.task/
# https://spdx.org/licenses/GPL-2.0
#

bomb () { echo "${0##*/}: ${@}" >&2; false; exit; }

(($# > 1)) && bomb "zero or one fql"
(($# == 0)) && set -- todo
timew start time/${1:?}
